# Generated by Django 4.1.3 on 2022-11-30 11:57

import category.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='URL', max_length=100, unique=True, verbose_name='URL')),
                ('description', models.CharField(help_text='Описание категории', max_length=255, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, help_text='Изображение категории', null=True, upload_to=category.utils.directory_path, verbose_name='Изображение категории')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['-name'],
            },
        ),
    ]
