# Generated by Django 4.1.3 on 2022-11-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
